django_test/django_test/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

from django.conf.urls import include

urlpatterns += [
    url(r'^scores/', include('scores.urls')),
]

from django.views.generic import RedirectView

urlpatterns += [
    url(r'^$', RedirectView.as_view(url='/scores/', permanent=True)),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django_test/scores/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^session/$', views.SessionView, name='session'),
    url(r'^loading/$', views.LoadingView, name='loading'),
]

django_test/scores/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Session(models.Model):
    homeTeam = models.CharField(max_length=100);
    awayTeam = models.CharField(max_length=100);

class Chat(models.Model):
    session = models.ForeignKey('Session', on_delete=models.SET_NULL, null=True)
    chat = models.CharField(max_length=100);

django_test/scores/forms.py
from django import forms

class NewSession(forms.Form):
    response = forms.BooleanField(initial=False, required=False)

    def clean_response(self):
        data = self.cleaned_data['response']

        return data

django_test/scores/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from random import randint
from django.views import generic

from .forms import NewSession
from .models import Session
from .models import Chat

# Create your views here.
def index(request):
    return render(
        request,
        'index.html',
        context={}
    )

def SessionView(request):
    if request.method == 'GET':
        id = request.GET.get('id', '')
        chat = request.GET.get('chat', '')
    session = Session.objects.get(id=id)
    if chat != '':
        Chat.objects.create(session=session, chat=chat)
    return render(
        request,
        'session.html',
        context={
            'session': session
        }
    )

def LoadingView(request):
    if request.method == 'GET':
        homeTeam = request.GET.get('homeTeam', '')
        awayTeam = request.GET.get('awayTeam', '')
    session = Session.objects.create(homeTeam=homeTeam, awayTeam=awayTeam)
    return render(
        request,
        'loading.html',
        context={'id': session.id}
    )

django_test/scores/templates/index.html
<!DOCTYPE html>
<html>
<body>
  <h3>New Session?</h3>
  <form action="loading/" method="get">
    <text>Home Team: </text>
    <input type="text" name="homeTeam" /> <br>
    <text>Away Team: </text>
    <input type="text" name="awayTeam" /> <br>
    <input type="hidden" name="id" value={{id}} />
    <input type="submit" value="YES" />
  </form>
</body>
</html>

django_test/scores/templates/loading.html
<!DOCTYPE html>
<html>
<body>
  <h3>Loading</h3>
  <script language="javascript">
    window.location.href = document.URL.substr(0,33) + "session/?id=" + {{id}}
  </script>
</body>
</html>

django_test/scores/templates/login.html
<!DOCTYPE html>
<html>
<body>
  <h3>Working</h3>
  <text>{{name}}</text>
</body>
</html>

django_test/scores/templates/session.html
<!DOCTYPE html>
<html>
<body>
  <h3>Session Details</h3>
  <text>{{session.homeTeam}} v. {{session.awayTeam}}</text>
  {% for copy in session.chat_set.all %}
  <ul>
    <li>
      <text>{{copy.chat}}</text>
    </li>
  </ul>
  {% endfor %}
  <form action="" method="get">
    <input type="hidden" name="id" value={{session.id}} />
    <input type="text" name="chat">
    <input type="submit" value="Submit"> <br>
    <input type="submit" value="Refresh">
  </form>
</body>
</html>